### PR TITLE
2023 style update, chat actions unjank and site moderation tools UI

### PR DESCRIPTION
**Pull request by Zekiah-A**
image

https://github.com/rslashplace2/rslashplace2.github.io/assets/73035340/db06fb12-e025-4d7e-958f-53ee267bfdf9

### CODE REVIEW

**Comment by Zekiah-A** [comment]
TODO: Make the moderation tools actually functional later

**Comment by dimaaac** [comment]
i hav a question: why do u pull request?

**Comment by Zekiah-A** [comment]
Because I would break the site if I pushed a half completed update :skull: . The site is served directly from this repo, if a half complete patch is pushed directly to this it will appear on the site instantly

**Comment by dimaaac** [comment]
ok lol

**Pull request merged**
