### PR TITLE
Implemented chat colours and improved chat look

### PR DESCRIPTION
**Pull request by Zekiah-A**

### CODE REVIEW

**Comment by Zekiah-A** [comment]
image
It looks good, trust me, it also picks a random appealing colour so it's based as well

**Review by rslashplace2 — CHANGES_REQUESTED** [review]
sanitize html. Your code has XSS vulnerabilities

**Comment by Zekiah-A** [comment]
image
I assumed you did here

**Comment by Zekiah-A** [comment]
ugh okay I will saniti**s**e then

**Comment by Zekiah-A** [comment]
Okay it is more saniti**s**ed than your mum was last night when I met her (I wasn't wearing any PPE)

**Pull request merged**
