### PR TITLE
[+] Attempt to improve code readability with JSDocs and more codebase changes.

### PR DESCRIPTION
**Pull request by embedvr**
I don't suggest auto merging this and urge you to check this repo for any errors. Most of the code is move around or are missing descriptions at the moment. Please check through it and make the appropriate edits.

Changes made:

- Organized code with Regions
- Put functions, browser events and websocket into their own areas. Bit more readable imo
- Assign all variables at the top of the file.
- Turned some code into switch statements for better readability.
- ~~Removed node modules LOL!~~ Reverted

I urge you to check these over and make sure it all works. As far as I can see, there are no bugs. Please also help with organizing the code at the bottom, not sure if it all belongs there.

### CODE REVIEW

**Comment by Zekiah-A** [comment]
Add back the node modules

**Comment by embedvr** [comment]
> Add back the node modules

npm install

**Comment by Zekiah-A** [comment]
Wow, the code here is quite clean, I just have some issues with how you have moved some things around

**Comment by Zekiah-A** [comment]
image
For example, it would make more sense to have all of the translation code in one place

image
Same case with the keybind code

**Comment by embedvr** [comment]
> image For example, it would make more sense to have all of the translation code in one place
> 
> image Same case with the keybind code

the translations are mostly in the same area other than the function moved in with other functions and the declarations for them at the top of the page. I am fine with moving the declarations down with the translations though.

keybind codes I were not as sure what they did. any suggestions where I should put it?

**Comment by embedvr** [comment]
I've moved around requested items. They have their own section now. 
This might have problems merging. I am not too sure.

**Pull request closed without merging**
